//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class GLOBAL_CONFIGURATION
    {
        public int config_id { get; set; }
        public int max_level { get; set; }
        public int clan_members { get; set; }
        public int limit { get; set; }
    }
}
