//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM
    {
        public int item_id { get; set; }
        public Nullable<int> player_id { get; set; }
        public string name { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<decimal> bonus_life { get; set; }
        public Nullable<decimal> bonus_strength { get; set; }
        public Nullable<decimal> bonus_speed { get; set; }
    
        public virtual PLAYER PLAYER { get; set; }
    }
}
