//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGIN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOGIN()
        {
            this.REGISTEREDPLAYER = new HashSet<REGISTEREDPLAYER>();
        }
    
        public int login_id { get; set; }
        public string user_email { get; set; }
        public string username { get; set; }
        public string name { get; set; }
        public string password { get; set; }
        public System.DateTime birthday { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REGISTEREDPLAYER> REGISTEREDPLAYER { get; set; }
    }
}
