//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class players_view
    {
        public int player_id { get; set; }
        public Nullable<int> login_id { get; set; }
        public Nullable<int> score { get; set; }
        public Nullable<int> level { get; set; }
        public Nullable<int> bank_balance { get; set; }
        public Nullable<int> life_points { get; set; }
        public Nullable<int> strength_points { get; set; }
        public Nullable<int> speed_points { get; set; }
        public string clan_name { get; set; }
        public Nullable<int> item_id { get; set; }
        public string name { get; set; }
    }
}
